//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCIFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCIFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string _api_facebook_access_token_expire_day {
            get {
                return ResourceManager.GetString("_api_facebook_access_token_expire_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 781330755269938.
        /// </summary>
        public static string _api_facebook_app_id {
            get {
                return ResourceManager.GetString("_api_facebook_app_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 89c2be2a447122fd7818fdcf0413ebc2.
        /// </summary>
        public static string _api_facebook_app_secret {
            get {
                return ResourceManager.GetString("_api_facebook_app_secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string _api_facebook_maximum_comments_to_retrieve_of_a_post {
            get {
                return ResourceManager.GetString("_api_facebook_maximum_comments_to_retrieve_of_a_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3014183050-mwJg6a3TfucgYBN8vleup28L3Zh1Ni1ZbHYdue8.
        /// </summary>
        public static string _api_twitter_access_token {
            get {
                return ResourceManager.GetString("_api_twitter_access_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dIM7xwVaqX3sjgh7Opl5k5K2fjxbXf3aNmcDyYmIIrxVc.
        /// </summary>
        public static string _api_twitter_access_token_secret {
            get {
                return ResourceManager.GetString("_api_twitter_access_token_secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20KCoXf5h80d4jfNx9XXrQkxM.
        /// </summary>
        public static string _api_twitter_consumer_key {
            get {
                return ResourceManager.GetString("_api_twitter_consumer_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vF6YCMfb5ltf93rYA76B8ORVhAJqEkZdA6yV1uvW0mIHVsRVwI.
        /// </summary>
        public static string _api_twitter_consumer_secret {
            get {
                return ResourceManager.GetString("_api_twitter_consumer_secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string _api_twitter_search_query_max_count {
            get {
                return ResourceManager.GetString("_api_twitter_search_query_max_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string _api_twitter_status_query_max_count {
            get {
                return ResourceManager.GetString("_api_twitter_status_query_max_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyDySsjf0V7XSzNbWII4zTJXq9CjkJ7EbeM.
        /// </summary>
        public static string _api_youtube_api_key {
            get {
                return ResourceManager.GetString("_api_youtube_api_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string _api_youtube_maximum_videos {
            get {
                return ResourceManager.GetString("_api_youtube_maximum_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Comms Diagnostics.
        /// </summary>
        public static string app_header {
            get {
                return ResourceManager.GetString("app_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Assessment.
        /// </summary>
        public static string assessment_create_new_title {
            get {
                return ResourceManager.GetString("assessment_create_new_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Details.
        /// </summary>
        public static string assessment_detail_window_title {
            get {
                return ResourceManager.GetString("assessment_detail_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment for:.
        /// </summary>
        public static string assessment_edit_title {
            get {
                return ResourceManager.GetString("assessment_edit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report last generated on .
        /// </summary>
        public static string assessment_report_date {
            get {
                return ResourceManager.GetString("assessment_report_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No report was generated for this assessment..
        /// </summary>
        public static string assessment_report_notgenerated {
            get {
                return ResourceManager.GetString("assessment_report_notgenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Details.
        /// </summary>
        public static string assessment_tab_1 {
            get {
                return ResourceManager.GetString("assessment_tab_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Facebook Assessment.
        /// </summary>
        public static string assessment_tab_1_fb_chkBox {
            get {
                return ResourceManager.GetString("assessment_tab_1_fb_chkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Page ID/Username.
        /// </summary>
        public static string assessment_tab_1_fb_txtBox_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_1_fb_txtBox_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string assessment_tab_1_organisation_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_1_organisation_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media Assessment.
        /// </summary>
        public static string assessment_tab_1_social_chkBox {
            get {
                return ResourceManager.GetString("assessment_tab_1_social_chkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy Assessment.
        /// </summary>
        public static string assessment_tab_1_strategy_chkBox {
            get {
                return ResourceManager.GetString("assessment_tab_1_strategy_chkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (e.g. June 2015).
        /// </summary>
        public static string assessment_tab_1_title_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_1_title_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Twitter Assessment.
        /// </summary>
        public static string assessment_tab_1_twitter_chkBox {
            get {
                return ResourceManager.GetString("assessment_tab_1_twitter_chkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Username.
        /// </summary>
        public static string assessment_tab_1_twitter_txtBox_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_1_twitter_txtBox_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience 1.
        /// </summary>
        public static string assessment_tab_1_website_audience1 {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_audience1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience 2.
        /// </summary>
        public static string assessment_tab_1_website_audience2 {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_audience2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience 3.
        /// </summary>
        public static string assessment_tab_1_website_audience3 {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_audience3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Assessment.
        /// </summary>
        public static string assessment_tab_1_website_chkBox {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_chkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Address (Home Page).
        /// </summary>
        public static string assessment_tab_1_website_home_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_home_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string assessment_tab_1_website_keywords {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page URL.
        /// </summary>
        public static string assessment_tab_1_website_page_url {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_page_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        public static string assessment_tab_1_website_scenario {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Pages.
        /// </summary>
        public static string assessment_tab_1_website_top_pages {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_top_pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Youtube Assessment.
        /// </summary>
        public static string assessment_tab_1_youtube_chkBox {
            get {
                return ResourceManager.GetString("assessment_tab_1_youtube_chkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Channel ID.
        /// </summary>
        public static string assessment_tab_1_youtube_txtBox_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_1_youtube_txtBox_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Worksheets.
        /// </summary>
        public static string assessment_tab_2 {
            get {
                return ResourceManager.GetString("assessment_tab_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook page name does not exist..
        /// </summary>
        public static string assessment_tab_2_alias_not_exist {
            get {
                return ResourceManager.GetString("assessment_tab_2_alias_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Authentication failed. Please try again..
        /// </summary>
        public static string assessment_tab_2_authentication_error {
            get {
                return ResourceManager.GetString("assessment_tab_2_authentication_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        public static string assessment_tab_2_col_1_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_2_col_1_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        public static string assessment_tab_2_col_2_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_2_col_2_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string assessment_tab_2_col_3_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_2_col_3_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Authentication failed..
        /// </summary>
        public static string assessment_tab_2_fb_auth_failed {
            get {
                return ResourceManager.GetString("assessment_tab_2_fb_auth_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve Facebook data. Please try again..
        /// </summary>
        public static string assessment_tab_2_fb_failed {
            get {
                return ResourceManager.GetString("assessment_tab_2_fb_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook failed. Please allocate more memory or close other applications..
        /// </summary>
        public static string assessment_tab_2_fb_out_of_memory {
            get {
                return ResourceManager.GetString("assessment_tab_2_fb_out_of_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook data retrieved successfully.
        /// </summary>
        public static string assessment_tab_2_fb_successful {
            get {
                return ResourceManager.GetString("assessment_tab_2_fb_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:
        ///
        ///Clicking Import Social Media button will regenerate a new Excel sheet. Previous assessments will be overwritten.
        ///
        ///To retrieve Facebook data, you might be asked to login to Facebook. Please use an authorised account to login.
        ///
        ///To retrieve Twitter data of an account, please grant MCIFramework access to that account by logging in and entering the one-time PIN number..
        /// </summary>
        public static string assessment_tab_2_notes {
            get {
                return ResourceManager.GetString("assessment_tab_2_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Facebook data.
        /// </summary>
        public static string assessment_tab_2_processing_fb {
            get {
                return ResourceManager.GetString("assessment_tab_2_processing_fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Twitter data.
        /// </summary>
        public static string assessment_tab_2_processing_twitter {
            get {
                return ResourceManager.GetString("assessment_tab_2_processing_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Twitter data for [.
        /// </summary>
        public static string assessment_tab_2_processing_twitter_different_name_1 {
            get {
                return ResourceManager.GetString("assessment_tab_2_processing_twitter_different_name_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ] instead of [.
        /// </summary>
        public static string assessment_tab_2_processing_twitter_different_name_2 {
            get {
                return ResourceManager.GetString("assessment_tab_2_processing_twitter_different_name_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ]..
        /// </summary>
        public static string assessment_tab_2_processing_twitter_different_name_3 {
            get {
                return ResourceManager.GetString("assessment_tab_2_processing_twitter_different_name_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Youtube data.
        /// </summary>
        public static string assessment_tab_2_processing_youtube {
            get {
                return ResourceManager.GetString("assessment_tab_2_processing_youtube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaching FB API calls limit. Please try again in 1 hour..
        /// </summary>
        public static string assessment_tab_2_reach_limit {
            get {
                return ResourceManager.GetString("assessment_tab_2_reach_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Authentication failed..
        /// </summary>
        public static string assessment_tab_2_twitter_auth_failed {
            get {
                return ResourceManager.GetString("assessment_tab_2_twitter_auth_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve Twitter data. Please try again.
        /// </summary>
        public static string assessment_tab_2_twitter_failed {
            get {
                return ResourceManager.GetString("assessment_tab_2_twitter_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter service is not available at the moment..
        /// </summary>
        public static string assessment_tab_2_twitter_not_available {
            get {
                return ResourceManager.GetString("assessment_tab_2_twitter_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaching Twitter API calls limit. Please try again in 15 minutes..
        /// </summary>
        public static string assessment_tab_2_twitter_reach_limit {
            get {
                return ResourceManager.GetString("assessment_tab_2_twitter_reach_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter data retrieved successfully.
        /// </summary>
        public static string assessment_tab_2_twitter_successful {
            get {
                return ResourceManager.GetString("assessment_tab_2_twitter_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter data retrieved successfully for [.
        /// </summary>
        public static string assessment_tab_2_twitter_successful_different_name_1 {
            get {
                return ResourceManager.GetString("assessment_tab_2_twitter_successful_different_name_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ]..
        /// </summary>
        public static string assessment_tab_2_twitter_successful_different_name_2 {
            get {
                return ResourceManager.GetString("assessment_tab_2_twitter_successful_different_name_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save result to Excel file. It is being used by another proces..
        /// </summary>
        public static string assessment_tab_2_unable_to_save {
            get {
                return ResourceManager.GetString("assessment_tab_2_unable_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve Youtube data. Please try again.
        /// </summary>
        public static string assessment_tab_2_youtube_failed {
            get {
                return ResourceManager.GetString("assessment_tab_2_youtube_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube data retrieved successfully.
        /// </summary>
        public static string assessment_tab_2_youtube_successful {
            get {
                return ResourceManager.GetString("assessment_tab_2_youtube_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        public static string assessment_tab_3 {
            get {
                return ResourceManager.GetString("assessment_tab_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        public static string assessment_tab_3_row1_titlle {
            get {
                return ResourceManager.GetString("assessment_tab_3_row1_titlle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string assessment_tab_3_row2_titlle {
            get {
                return ResourceManager.GetString("assessment_tab_3_row2_titlle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string assessment_tab_3_row3_titlle {
            get {
                return ResourceManager.GetString("assessment_tab_3_row3_titlle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the required files.
        /// </summary>
        public static string assessment_tab_3_select_required_files {
            get {
                return ResourceManager.GetString("assessment_tab_3_select_required_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Worksheets.
        /// </summary>
        public static string assessment_tab_3_titlle {
            get {
                return ResourceManager.GetString("assessment_tab_3_titlle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload is completed !.
        /// </summary>
        public static string assessment_tab_3_upload_complete {
            get {
                return ResourceManager.GetString("assessment_tab_3_upload_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter PIN .
        /// </summary>
        public static string assessment_twitter_auth_provide_pin {
            get {
                return ResourceManager.GetString("assessment_twitter_auth_provide_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Assessment.
        /// </summary>
        public static string btn_create_new_assessment {
            get {
                return ResourceManager.GetString("btn_create_new_assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btn_search {
            get {
                return ResourceManager.GetString("btn_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save .
        /// </summary>
        public static string btn_tab_1_save {
            get {
                return ResourceManager.GetString("btn_tab_1_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Continue.
        /// </summary>
        public static string btn_tab_1_save_and_continue {
            get {
                return ResourceManager.GetString("btn_tab_1_save_and_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Strategy Worksheet.
        /// </summary>
        public static string btn_tab_2_download_column_1 {
            get {
                return ResourceManager.GetString("btn_tab_2_download_column_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Social Media Worksheet.
        /// </summary>
        public static string btn_tab_2_download_column_2 {
            get {
                return ResourceManager.GetString("btn_tab_2_download_column_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Web Worksheet.
        /// </summary>
        public static string btn_tab_2_download_column_3 {
            get {
                return ResourceManager.GetString("btn_tab_2_download_column_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Social Media Data.
        /// </summary>
        public static string btn_tab_2_import_column_2 {
            get {
                return ResourceManager.GetString("btn_tab_2_import_column_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Report.
        /// </summary>
        public static string btn_tab_3_downloadreport {
            get {
                return ResourceManager.GetString("btn_tab_3_downloadreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Worksheets.
        /// </summary>
        public static string btn_tab_3_uploadworksheets {
            get {
                return ResourceManager.GetString("btn_tab_3_uploadworksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one social media platform..
        /// </summary>
        public static string confirm_at_least_one_platform {
            get {
                return ResourceManager.GetString("confirm_at_least_one_platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the assessment?.
        /// </summary>
        public static string confirm_delete_assessment {
            get {
                return ResourceManager.GetString("confirm_delete_assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string confirm_delete_assessment_confirm {
            get {
                return ResourceManager.GetString("confirm_delete_assessment_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Organisation / Title.
        /// </summary>
        public static string dashboard_search_title {
            get {
                return ResourceManager.GetString("dashboard_search_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Dashboard.
        /// </summary>
        public static string dashboard_title {
            get {
                return ResourceManager.GetString("dashboard_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard_window_title {
            get {
                return ResourceManager.GetString("dashboard_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string error_text_color {
            get {
                return ResourceManager.GetString("error_text_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media Assessment.xlsx.
        /// </summary>
        public static string excel_social {
            get {
                return ResourceManager.GetString("excel_social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy Assessment.xlsx.
        /// </summary>
        public static string excel_strategy {
            get {
                return ResourceManager.GetString("excel_strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Assessment.xlsx.
        /// </summary>
        public static string excel_web {
            get {
                return ResourceManager.GetString("excel_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every metric is a score from 0-10. A score of 10 means the ministry/agency is doing as well as can be expected based on best practice and the organisation&apos;s nature..
        /// </summary>
        public static string homeroot_description {
            get {
                return ResourceManager.GetString("homeroot_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to read the framework results.
        /// </summary>
        public static string homeroot_title {
            get {
                return ResourceManager.GetString("homeroot_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Authentication completed.
        /// </summary>
        public static string message_twiiter_auth_completed {
            get {
                return ResourceManager.GetString("message_twiiter_auth_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Authentication failed.
        /// </summary>
        public static string message_twiiter_auth_failed {
            get {
                return ResourceManager.GetString("message_twiiter_auth_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field cannot be blank..
        /// </summary>
        public static string model_validation_blank_field {
            get {
                return ResourceManager.GetString("model_validation_blank_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be after start date.
        /// </summary>
        public static string model_validation_end_date {
            get {
                return ResourceManager.GetString("model_validation_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Page ID is required..
        /// </summary>
        public static string model_validation_fb_user_name {
            get {
                return ResourceManager.GetString("model_validation_fb_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name is required..
        /// </summary>
        public static string model_validation_organisation {
            get {
                return ResourceManager.GetString("model_validation_organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the required fields.
        /// </summary>
        public static string model_validation_please_fill_fields {
            get {
                return ResourceManager.GetString("model_validation_please_fill_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be before end date.
        /// </summary>
        public static string model_validation_start_date {
            get {
                return ResourceManager.GetString("model_validation_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string model_validation_title {
            get {
                return ResourceManager.GetString("model_validation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter username is required..
        /// </summary>
        public static string model_validation_twitter_user_name {
            get {
                return ResourceManager.GetString("model_validation_twitter_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid date..
        /// </summary>
        public static string model_validation_valid_date {
            get {
                return ResourceManager.GetString("model_validation_valid_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid URL..
        /// </summary>
        public static string model_validation_valid_url {
            get {
                return ResourceManager.GetString("model_validation_valid_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube ID is required..
        /// </summary>
        public static string model_validation_youtube_id {
            get {
                return ResourceManager.GetString("model_validation_youtube_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string processing_text_color {
            get {
                return ResourceManager.GetString("processing_text_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Login to Twitter using assessee&apos;s account to generate authentication PIN. The authentication PIN is required for pulling data from Twitter.
        ///
        ///2. Copy the PIN generated by Twitter (after login) and paste it to the text box at the bottom of the page, and then click Submit to proceed..
        /// </summary>
        public static string twitter_auth_instructions {
            get {
                return ResourceManager.GetString("twitter_auth_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedDate.
        /// </summary>
        public static string value_dasboard_grid_default_sort_column {
            get {
                return ResourceManager.GetString("value_dasboard_grid_default_sort_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ascending.
        /// </summary>
        public static string value_dasboard_grid_default_sort_direction {
            get {
                return ResourceManager.GetString("value_dasboard_grid_default_sort_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string value_dashboard_page_default_row_count {
            get {
                return ResourceManager.GetString("value_dashboard_page_default_row_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string warning_text_color {
            get {
                return ResourceManager.GetString("warning_text_color", resourceCulture);
            }
        }
    }
}
