//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCIFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCIFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Comms Diagnostics.
        /// </summary>
        public static string app_header {
            get {
                return ResourceManager.GetString("app_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Assessment.
        /// </summary>
        public static string assessment_create_new_title {
            get {
                return ResourceManager.GetString("assessment_create_new_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Details.
        /// </summary>
        public static string assessment_detail_window_title {
            get {
                return ResourceManager.GetString("assessment_detail_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment for:.
        /// </summary>
        public static string assessment_edit_title {
            get {
                return ResourceManager.GetString("assessment_edit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Details.
        /// </summary>
        public static string assessment_tab_1 {
            get {
                return ResourceManager.GetString("assessment_tab_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Facebook Assessment.
        /// </summary>
        public static string assessment_tab_1_fb_chkBox {
            get {
                return ResourceManager.GetString("assessment_tab_1_fb_chkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Page ID/Username.
        /// </summary>
        public static string assessment_tab_1_fb_txtBox_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_1_fb_txtBox_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string assessment_tab_1_organisation_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_1_organisation_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media Assessment.
        /// </summary>
        public static string assessment_tab_1_social_chkBox {
            get {
                return ResourceManager.GetString("assessment_tab_1_social_chkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy Assessment.
        /// </summary>
        public static string assessment_tab_1_strategy_chkBox {
            get {
                return ResourceManager.GetString("assessment_tab_1_strategy_chkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (e.g. June 2015).
        /// </summary>
        public static string assessment_tab_1_title_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_1_title_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Twitter Assessment.
        /// </summary>
        public static string assessment_tab_1_twitter_chkBox {
            get {
                return ResourceManager.GetString("assessment_tab_1_twitter_chkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Username.
        /// </summary>
        public static string assessment_tab_1_twitter_txtBox_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_1_twitter_txtBox_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience 1.
        /// </summary>
        public static string assessment_tab_1_website_audience1 {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_audience1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience 2.
        /// </summary>
        public static string assessment_tab_1_website_audience2 {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_audience2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience 3.
        /// </summary>
        public static string assessment_tab_1_website_audience3 {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_audience3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Assessment.
        /// </summary>
        public static string assessment_tab_1_website_chkBox {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_chkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Address (Home Page).
        /// </summary>
        public static string assessment_tab_1_website_home_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_home_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string assessment_tab_1_website_keywords {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page URL.
        /// </summary>
        public static string assessment_tab_1_website_page_url {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_page_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        public static string assessment_tab_1_website_scenario {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Pages.
        /// </summary>
        public static string assessment_tab_1_website_top_pages {
            get {
                return ResourceManager.GetString("assessment_tab_1_website_top_pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Youtube Assessment.
        /// </summary>
        public static string assessment_tab_1_youtube_chkBox {
            get {
                return ResourceManager.GetString("assessment_tab_1_youtube_chkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Channel ID.
        /// </summary>
        public static string assessment_tab_1_youtube_txtBox_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_1_youtube_txtBox_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Worksheets.
        /// </summary>
        public static string assessment_tab_2 {
            get {
                return ResourceManager.GetString("assessment_tab_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        public static string assessment_tab_2_col_1_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_2_col_1_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        public static string assessment_tab_2_col_2_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_2_col_2_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string assessment_tab_2_col_3_lbl {
            get {
                return ResourceManager.GetString("assessment_tab_2_col_3_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:
        /// 
        ///Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        /// 
        ///Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..
        /// </summary>
        public static string assessment_tab_2_notes {
            get {
                return ResourceManager.GetString("assessment_tab_2_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        public static string assessment_tab_3 {
            get {
                return ResourceManager.GetString("assessment_tab_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        public static string assessment_tab_3_row1_titlle {
            get {
                return ResourceManager.GetString("assessment_tab_3_row1_titlle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string assessment_tab_3_row2_titlle {
            get {
                return ResourceManager.GetString("assessment_tab_3_row2_titlle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string assessment_tab_3_row3_titlle {
            get {
                return ResourceManager.GetString("assessment_tab_3_row3_titlle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Worksheets.
        /// </summary>
        public static string assessment_tab_3_titlle {
            get {
                return ResourceManager.GetString("assessment_tab_3_titlle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Assessment.
        /// </summary>
        public static string btn_create_new_assessment {
            get {
                return ResourceManager.GetString("btn_create_new_assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btn_search {
            get {
                return ResourceManager.GetString("btn_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Continue.
        /// </summary>
        public static string btn_tab_1_save {
            get {
                return ResourceManager.GetString("btn_tab_1_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Strategy Worksheet.
        /// </summary>
        public static string btn_tab_2_download_column_1 {
            get {
                return ResourceManager.GetString("btn_tab_2_download_column_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Social Media Worksheet.
        /// </summary>
        public static string btn_tab_2_download_column_2 {
            get {
                return ResourceManager.GetString("btn_tab_2_download_column_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Social Media Data.
        /// </summary>
        public static string btn_tab_2_import_column_2 {
            get {
                return ResourceManager.GetString("btn_tab_2_import_column_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Web Worksheet.
        /// </summary>
        public static string btn_tab_3_download_column_3 {
            get {
                return ResourceManager.GetString("btn_tab_3_download_column_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Report.
        /// </summary>
        public static string btn_tab_3_downloadreport {
            get {
                return ResourceManager.GetString("btn_tab_3_downloadreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Worksheets.
        /// </summary>
        public static string btn_tab_3_uploadworksheets {
            get {
                return ResourceManager.GetString("btn_tab_3_uploadworksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Organisation / Title.
        /// </summary>
        public static string dashboard_search_title {
            get {
                return ResourceManager.GetString("dashboard_search_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Dashboard.
        /// </summary>
        public static string dashboard_title {
            get {
                return ResourceManager.GetString("dashboard_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard_window_title {
            get {
                return ResourceManager.GetString("dashboard_window_title", resourceCulture);
            }
        }
    }
}
